openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/customerpayme/ZuriChat/1.0.0
  - description: Zuri Chat Core API
    url: 'https://api.zuri-app-url.com/v1'
info:
  version: 1.0.0
  title: Zuri Chat Core API
  description: Zuri Chat is an open source slack clone. However, it offers a lot more functionality via a plugin system where each room can be provided by a different plugin provider.
  contact:
    email: developer@zuri.chat
tags:
  - name: app
    description: Api for the Apps
paths:
  /sidebar:
    get:
      tags:
        - app
      summary: retrieves all sidebar items that should be displayed on behalf of this app
      operationId: getSidebar
      description: |
        This will return everything that needs to be shown in the sidebar
      parameters:
        - in: query
          name: userID
          description: provide the userid of the authenticated person. 
          required: true
          schema:
            type: string
        - in: query
          name: userToken
          description: provide a user token that this app will use to validate that the call is genuine. It will call back Zuri Core
          schema:
            type: string
      responses:
        '200':
          description: a list of sidebar items to be displayed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SidebarItem'
        '400':
          description: bad input parameter

  /show:
    post:
      tags:
        - app
      summary: displays the main body of the app
      operationId: showApp
      description: |
        Queries to get the full html for the app that will be shown on the right
        hand side
      parameters:
        - in: query
          name: userID
          description: The ID of the particular user viewing this app
          required: true
          schema:
            type: string
        - in: query
          name: userToken
          description: an authentication token
          schema:
            type: string
            
      requestBody:
        description: The structure for the entire request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppRequest'
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'
        '400':
          description: bad input parameter

  /organizations:
    get:
      summary: Displays a list of organizations
      security:
        - bearerAuth: [] 
      responses:
        '200':
          description: Successfuly returned list of organizations, including an empty array if there are no organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post: 
      summary: Create an organization
      security:
        - bearerAuth: [] 
      requestBody:
        description: The structure for the entire request
        content:
          'application/json':
            schema:
              properties:
                user_id:
                  type: integer
                  description: This is the id of the owner(creator) of the organization
                  example: 2
                name:
                  type: string
                  description: Name of the organization
                  example: 'hng@email.com'
                email:
                  type: string
                  description: Email of the organization
                  example: 'hng@email.com'
                organization_logo_url:
                  type: string
                  description: Url of organization logo
                  example: 'http://api.zuri.chat/media/fddpofdg.svg'
                organization_settings:
                  type: json
                  description: Json object of organization settings
                  example: {"global_settings": {"allow_user_add_plugins": true, "allow_only_admin_invite": true}, "plugin_settings": {"chess_plugin": {"allow_in_every_channel": false}}}
            required: 
              - user_id
              - email
      responses:
        '201':
          description: Organization successfully created
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request, e.g wrong user id
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'

  /organizations/{organization_id}:
    get: 
      summary: Get an organization
      security:
        - bearerAuth: [] 
      parameters:
        - $ref: '#/components/parameters/organization_id'
      responses:
        '200':
          description: Organization successfully returned
            content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request, e.g wrong user id
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    put: 
      summary: Update organization information
      security:
        - bearerAuth: [] 
      parameters:
        - $ref: '#/components/parameters/organization_id'
      requestBody:
        description: The structure for the entire request
        content:
          'application/json':
      responses:
        '200':
          description: Organization successfully returned
            content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request, e.g wrong user id
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'

  /organizations/{organization_id}/users:
    get: 
      summary: Get a list of users in an organization
      security:
        - bearerAuth: [] 
      parameters:
        - $ref: '#/components/parameters/organization_id'
      responses:
        '200':
          description: Organization successfully returned
            content:
              'application/json':
                schema:
                  type: array
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Organization with organization_id not found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    post: 
      summary: Add user to an organization
      security:
        - bearerAuth: [] 
      parameters:
        - $ref: '#/components/parameters/organization_id'
      requestBody:
        description: The structure for the entire request
        content:
          'application/json':
            schema:
              properties:
                user_id:
                  type: integer
                  description: This is the id of the user to be added to the organization
                  example: 2
      responses:
        '201':
          description: Organization successfully returned
            content:
              'application/json':
                schema:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'

  /organizations/{organization_id}/users/{user_id}:
    put: 
      summary: Update user
      description: This endpoint will be used to update the user's organization information. e.g user roles and permissions
      security:
        - bearerAuth: [] 
      parameters:
        - $ref: '#/components/parameters/organization_id'
        - $ref: '#/components/parameters/user_id'
      requestBody:
        description: The structure for the entire request
        required: true
        content:
          'application/json':
            schema:
              properties:
                data:
                  type: any
                  description: Data to be updated
                  example: 2
      responses:
        '200':
          description: User successfully updated
            content:
              'application/json':
                schema:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    delete: 
      summary: Delete user
      description: Remove a user from an organization
      security:
        - bearerAuth: [] 
      parameters:
        - $ref: '#/components/parameters/organization_id'
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: User successfully deleted
            content:
              'application/json':
                schema:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    organization_id:
      in: path
      name: organization_id
      required: true
      schema:
        type: integer
  schemas:
    SidebarItem:
      type: object
      required:
        - id
        - title
        - icon
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        title:
          type: string
          example: DM
        icon:
          type: string
          example: user-profile-image
          
    AppRequest:
      properties:
        users_in_room:
          type: string
          example: Private Messages
        data_endpoint:
          type: string
          example: 'api.zuri.chat/data'
        messaging_endpoint:
          type: string
          example: 'api.zuri.chat/messaging'
      type: object
      
    App:
      required:
        - name
      properties:
        title:
          type: string
          example: Private Messages
        fullhtml:
          type: string
          example: '<html><head>...'
        version:
          type: string
          example: 1.01
      type: object

    Organization:
      type: object
      properties:
        user_id:
          type: integer
          example: 12
        name:
          type: string
          example: 'HNG'
        email:
          type: string
          example: 'hng@email.com'
        organization_logo_url:
          type: integer
          example: 12
        organization_settings:
          type: json
          example: {"global_settings": {"allow_user_add_plugins": true, "allow_only_admin_invite": true}, "plugin_settings": {"chess_plugin": {"allow_in_every_channel": false}}}